name: ci

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Docker Maven meta
        id: maven
        uses: docker/metadata-action@v4
        with:
          images: |
            vedant/maven
          tags: |
            type=semver,pattern={{version}}
      -
        name: Docker NPM meta
        id: npm
        uses: docker/metadata-action@v4
        with:
          images: |
            vedant/npm
          tags: |
            type=semver,pattern={{version}}
      -
        name: Docker alpine meta
        id: alpine
        uses: docker/metadata-action@v4
        with:
          images: |
            vedant/my-alpine
          tags: |
            type=semver,pattern={{version}}
      -
        name: Build Alpine
        uses: docker/build-push-action@v3
        with:
          context: alpine/.
          push: false
          tags: ${{ steps.maven.outputs.tags }}
          file: alpine/Dockerfile.alpine
          labels: ${{ steps.maven.outputs.labels }}
      -
        name: Build Maven
        uses: docker/build-push-action@v3
        with:
          context: maven/.
          push: false
          tags: ${{ steps.maven.outputs.tags }}
          file: maven/Dockerfile.maven
          labels: ${{ steps.maven.outputs.labels }}
          
      -
        name: Build NPM
        uses: docker/build-push-action@v3
        with:
          context: npm/.
          push: false
          tags: ${{ steps.npm.outputs.tags }}
          labels: ${{ steps.npm.outputs.labels }}
          file: npm/Dockerfile.npm
