name: ci

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build Alpine
        uses: docker/build-push-action@v3
        with:
          context: alpine/.
          push: false
          file: alpine/Dockerfile.alpine
          outputs: type=docker,dest=/tmp/base.tar
          tags: vedant/my-alpine:latest
      -
        name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: baseimage
          path: /tmp/base.tar

  maven:
    runs-on: ubuntu-latest
    needs: base
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3 
      -
        name: Docker Maven meta
        id: maven
        uses: docker/metadata-action@v4
        with:
          images: vedant/maven
          tags: type=sha
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: baseimage
          path: /tmp
      -
        name: Load image
        run: |
          docker load --input /tmp/base.tar
          docker image ls -a
      -
        name: Build Maven
        run: |
          docker build -f maven/Dockerfile.maven -t vedant/maven maven/.
  npm:
    runs-on: ubuntu-latest
    needs: base
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker NPM meta
        id: npm
        uses: docker/metadata-action@v4
        with:
          images: vedant/npm
          tags: type=sha
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: baseimage
          path: /tmp
      -
        name: Load image
        run: |
          docker load --input /tmp/base.tar
          docker image ls -a

      -
        name: Build NPM
        run: |
          docker build -f npm/Dockerfile.npm -t vedant/npm npm/.

