name: ci

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build Alpine
        uses: docker/build-push-action@v3
        with:
          context: alpine/.
          push: false
          file: alpine/Dockerfile.alpine
          outputs: type=docker,dest=/tmp/base.tar
          tags: my-base-image:latest
      -
        name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: baseimage
          path: /tmp/base.tar

  maven:
    runs-on: ubuntu-latest
    needs: base
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: baseimage
          path: /tmp
      -
        name: Load image
        run: |
          docker load --input /tmp/base.tar
          docker image ls -a
      -
        name: Docker Maven meta
        id: maven
        uses: docker/metadata-action@v4
        with:
          images: vedant/maven
          tags: type=sha
      -
        name: Build Maven
        uses: docker/build-push-action@v3
        with:
          context: maven/.
          push: false
          build-contexts: vedant/my-alpine=docker-image://my-base-image:latest
          tags: ${{ steps.maven.outputs.tags }}
          file: maven/Dockerfile.maven
          labels: ${{ steps.maven.outputs.labels }}
  npm:
    runs-on: ubuntu-latest
    needs: base
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: baseimage
          path: /tmp
      -
        name: Load image
        run: |
          docker load --input /tmp/base.tar
          docker image ls -a
      -
        name: Docker NPM meta
        id: npm
        uses: docker/metadata-action@v4
        with:
          images: vedant/npm
          tags: type=sha
      -
        name: Build NPM
        uses: docker/build-push-action@v3
        with:
          context: npm/.
          build-contexts: vedant/my-alpine=docker-image://my-base-image:latest
          push: false
          tags: ${{ steps.npm.outputs.tags }}
          labels: ${{ steps.npm.outputs.labels }}
          file: npm/Dockerfile.npm

